### ISSUE TITLE
How to add svg image(of a $ icon) inside an input box/element?

### ISSUE THREAD

**Issue by milanjain2208** [milanjain2208/tip-calculator#1]
Expected Output
<img width="171" alt="expected" src="https://user-images.githubusercontent.com/54152827/134583930-f634f488-e72b-4ab7-a446-1014ddcb3184.PNG">
My Output
<img width="219" alt="my_input-box" src="https://user-images.githubusercontent.com/54152827/134583938-4cd48712-cafe-4638-b87a-5f2bcbbe4dae.PNG">

I am trying to do something like this in my css.
#input-amount:before {
    content: url('icon-dollar.svg');
}
This doesn't work.

**Comment by jahgath** [comment]
```css
.currencyinput {
    border: 1px inset #ccc;
}
.currencyinput input {
    border: 0;
}

<span class="currencyinput">$<input type="text" name="currency"></span>

````
Try editing this code to your fit. Example Output:
![image](https://user-images.githubusercontent.com/53384211/134658163-cb464f67-2b90-4288-90f4-17a3290d960d.png)
````

**Comment by milanjain2208** [comment]
Hi @jahgath. Thanks for the reply. But the issue is that I have a dollar svg image(https://github.com/milanjain2208/tip-calculator/blob/main/images/icon-dollar.svg) and I want to left align it inside an input box. [This is a link of what I am trying to achieve](https://www.frontendmentor.io/challenges/tip-calculator-app-ugJNGbJUX)  and [this is what I have done](https://milanjain2208.github.io/tip-calculator/).

**Comment by milanjain2208** [comment]
@jahgath from your comment I did this
```css
<span class="dollar-container"></span>`
<input type="text" id="input-amount" placeholder="0">

.dollar-container {
    position: relative;
}
.dollar-container:before {
    content: url('./images/icon-dollar.svg');
    position: absolute;
    top: 10%;
    padding-left: 10px;
}
```
It worked. But I don't know if this is the best way to do this. And also am not able to resize (decrease) the size of the svg.
